sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sreenivas-git/docker-react -f Dockerfile.dev .

script:
  - docker run sreenivas-git/docker-react npm run test -- --coverage
